### Создаем факультет
POST http://localhost:8080/faculty
Content-Type: application/json

{
  "name": "FacultyFaculty",
  "color": "white"
}

### Создаем студента
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "Tester4",
  "age": 22,
  "faculty": {
    "id": 24
  }
}

### Посчитать количество студентов
GET http://localhost:8080/student/all/count